kind: pipeline
type: docker
name: default

steps:
# - name: send-tags-to-tags-file
#   image: node
#   commands:
#     - echo -n "$(date +'%Y-%m-%d_%H-%M')_${DRONE_COMMIT}, latest" > .tags
- name: backend
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password 
    repo: waglay14/backend
    tags: 
      - "${date +'%Y-%m-%d_%H-%M-%S'}_${DRONE_COMMIT}"
      - latest
    dockerfile: ./backend/Dockerfile
    context: ./backend
- name: frontend
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password 
    repo: waglay14/frontend
    tags: 
      - "$(date +'%Y-%m-%d_%H-%M-%S')_${DRONE_COMMIT}"
      - latest
    dockerfile: ./frontend/Dockerfile
    context: ./frontend
