kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password 
    repo: waglay14/backend
    tags: 
      - ${DRONE_TAG}
      - latest
    dockerfile: ./backend/Dockerfile
    context: ./backend
