kind: pipeline
type: docker
name: mern_stack_test

steps:
- name: send-tags-to-tags-file
  image: nginx:alpine
  when:
    branch:
      - dev
  commands:
    - echo -n "$(date +'%Y-%m-%d_%H-%M-%S')_${DRONE_COMMIT}, latest" > .tags
    
- name: backend
  when:
    branch:
      - dev
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password 
    repo: waglay14/backend
    dockerfile: ./backend/Dockerfile
    context: ./backend
    
- name: frontend
  image: plugins/docker
  when:
    branch:
      - main
  settings:
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password 
    repo: waglay14/frontend
    dockerfile: ./frontend/Dockerfile
    context: ./frontend
